/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SibeliusGovernance } from "./SibeliusGovernance";

export { SibeliusGovernance__factory } from "./factories/SibeliusGovernance__factory";
