/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  SibeliusGovernance,
  SibeliusGovernanceInterface,
} from "../SibeliusGovernance";

const _abi = [
  {
    inputs: [],
    name: "doSomething",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50606d80601d6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80638269267914602d575b600080fd5b60336035565b005b56fea2646970667358221220b7296dc51d59bc260585b65d3202656b47441aca67d3f5c8b114eccd1de56e8964736f6c63430008070033";

export class SibeliusGovernance__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<SibeliusGovernance> {
    return super.deploy(overrides || {}) as Promise<SibeliusGovernance>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): SibeliusGovernance {
    return super.attach(address) as SibeliusGovernance;
  }
  connect(signer: Signer): SibeliusGovernance__factory {
    return super.connect(signer) as SibeliusGovernance__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SibeliusGovernanceInterface {
    return new utils.Interface(_abi) as SibeliusGovernanceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SibeliusGovernance {
    return new Contract(address, _abi, signerOrProvider) as SibeliusGovernance;
  }
}
